/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrental;
import com.mysql.cj.protocol.Resultset;
import java.awt.HeadlessException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author KAVEEN
 */
public final class cars extends javax.swing.JFrame {

    /**
     * Creates new form cars
     * @throws java.sql.SQLException
     */
    public cars() throws SQLException {
        initComponents();
        Displaycars();
         
        
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    Connection con ;
    Statement st;
    Resultset Rs;
    PreparedStatement pst;

    

    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblAjCarRental = new javax.swing.JLabel();
        lblAjCarRental1 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblRentCar = new javax.swing.JLabel();
        lblReturnCar = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        lblAjCarRental2 = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        Reg = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblAjCarRental8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        lblAjCarRental.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblAjCarRental.setForeground(new java.awt.Color(51, 51, 51));
        lblAjCarRental.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAjCarRental.setText("Service");
        lblAjCarRental.setName("lblAJCarRental"); // NOI18N

        lblAjCarRental1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblAjCarRental1.setForeground(new java.awt.Color(51, 51, 51));
        lblAjCarRental1.setText("AJ Car Rental");
        lblAjCarRental1.setName("lblAJCarRental"); // NOI18N

        lblImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\KAVEEN\\Desktop\\New folder (6)\\images_(2)-transformed.png")); // NOI18N

        lblCustomer.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomer.setText("Customer");
        lblCustomer.setName("lblAJCarRental"); // NOI18N
        lblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerMouseClicked(evt);
            }
        });

        lblRentCar.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblRentCar.setForeground(new java.awt.Color(255, 255, 255));
        lblRentCar.setText("Rent Car");
        lblRentCar.setName("lblAJCarRental"); // NOI18N
        lblRentCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRentCarMouseClicked(evt);
            }
        });

        lblReturnCar.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblReturnCar.setForeground(new java.awt.Color(255, 255, 255));
        lblReturnCar.setText("Return Car");
        lblReturnCar.setName("lblAJCarRental"); // NOI18N
        lblReturnCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReturnCarMouseClicked(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 51));
        btnLogout.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAjCarRental1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCustomer)
                            .addComponent(lblRentCar)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblAjCarRental))
                            .addComponent(lblReturnCar)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblImage)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAjCarRental1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAjCarRental)
                .addGap(125, 125, 125)
                .addComponent(lblCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRentCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReturnCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 51));
        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
        );

        lblAjCarRental2.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblAjCarRental2.setForeground(new java.awt.Color(255, 0, 51));
        lblAjCarRental2.setText("Manage Cars");
        lblAjCarRental2.setName("lblAJCarRental"); // NOI18N

        lblRegister.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 0, 51));
        lblRegister.setText("Registration Num");
        lblRegister.setName("lblAJCarRental"); // NOI18N

        Reg.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Reg.setForeground(new java.awt.Color(255, 0, 51));

        txtBrand.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtBrand.setForeground(new java.awt.Color(255, 0, 51));

        lblBrand.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(255, 0, 51));
        lblBrand.setText("Brand");
        lblBrand.setName("lblAJCarRental"); // NOI18N

        lblModel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblModel.setForeground(new java.awt.Color(255, 0, 51));
        lblModel.setText("Model");
        lblModel.setName("lblAJCarRental"); // NOI18N

        txtModel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtModel.setForeground(new java.awt.Color(255, 0, 51));

        lblPrice.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 0, 51));
        lblPrice.setText("Price");
        lblPrice.setName("lblAJCarRental"); // NOI18N

        txtPrice.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 0, 51));

        lblStatus.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 0, 51));
        lblStatus.setText("Status");
        lblStatus.setName("lblAJCarRental"); // NOI18N

        cmbStatus.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmbStatus.setForeground(new java.awt.Color(255, 0, 51));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Booked", "Available" }));

        btnDelete.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 0, 51));
        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 0, 51));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 51));
        btnReset.setText("Clear");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblAjCarRental8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblAjCarRental8.setForeground(new java.awt.Color(255, 0, 51));
        lblAjCarRental8.setText("Car List");
        lblAjCarRental8.setName("lblAJCarRental"); // NOI18N

        tblCar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Registration", "Brand", "Model", "Status", "Price"
            }
        ));
        tblCar.setRowHeight(25);
        jScrollPane1.setViewportView(tblCar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Reg))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                                .addGap(42, 42, 42))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(232, 232, 232)
                                        .addComponent(lblAjCarRental2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addComponent(btnsave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnReset)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(lblAjCarRental8)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAjCarRental2)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRegister)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBrand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModel)
                                    .addComponent(lblStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnsave)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addComponent(lblAjCarRental8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
String url = "jdbc:mysql://localhost:3306/ajcar";
        String username = "Kaveen";
        String password = "123";

        // SQL query to delete voter details
        String sql = "DELETE FROM cartbl WHERE carReg = ?";

        try (Connection conn = DriverManager.getConnection(url, username, password);
            PreparedStatement stmt = conn.prepareStatement(sql)) {
            String carR = Reg.getText();
            stmt.setString(1, carR);

            // Execute the delete query
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(rootPane, "user account deleted successfully.");
                Displaycars();
                btnResetActionPerformed(evt);
                
                

            } else {
                JOptionPane.showMessageDialog(rootPane, "No matching user details found.");

            }

        } catch (SQLException e) {
        }
          // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        
        
        
String url = "jdbc:mysql://localhost:3306/ajcar";
String username = "Kaveen";
String password = "123";

Connection connection = null; // Initialize the connection

try {
    connection = DriverManager.getConnection(url, username, password);

    String sql = "UPDATE cartbl SET brand = ?, model = ?, status = ?, price = ? WHERE carReg = ?";
    PreparedStatement statement = connection.prepareStatement(sql);
    statement.setString(1, txtBrand.getText());
    statement.setString(2, txtModel.getText());
    statement.setString(3, cmbStatus.getSelectedItem().toString());
    statement.setInt(4, Integer.parseInt(txtPrice.getText()));
    statement.setString(5, Reg.getText());

    int rowsAffected = statement.executeUpdate();
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(null, "Updated successfully.");
        Displaycars();
        btnResetActionPerformed(evt);
        
    } else {
        JOptionPane.showMessageDialog(null, "No records were updated.", "Update Error", JOptionPane.WARNING_MESSAGE);
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
} catch (HeadlessException | NumberFormatException exception) {
    JOptionPane.showMessageDialog(null, "Data cannot be updated because of: " + exception, "Update Error", JOptionPane.ERROR_MESSAGE);
} finally {
    if (connection != null) {
        try {
            connection.close(); // Close the connection when done
        } catch (SQLException e) {
            // Handle any potential closing error
            e.printStackTrace();
        }
    }
}



    }//GEN-LAST:event_btnEditActionPerformed

    
    private void Displaycars()
    {
        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        model.setRowCount(0);
    
        try {
            String url = "jdbc:mysql://localhost:3306/ajcar";
            String username = "Kaveen";
            String password = "123";

            try (Connection conn = DriverManager.getConnection(url, username, password)) {
                String sql = "SELECT * FROM cartbl" ;
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    
                    try (ResultSet rs = stmt.executeQuery()) {
                        while (rs.next()) {
                            String regno = rs.getString("carReg");
                            String brand = rs.getString("brand");
                            String Model = rs.getString("model");
                            String status = rs.getString("status");
                            String price = rs.getString("price");
                            Object[] rowData = { regno, brand, Model, status,price };
                            model.addRow(rowData);
                        }
                    }
                }
            }
        } catch (SQLException e) {
}
  }
            
            
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

    
     try {
    String reg = Reg.getText();
    String brand = txtBrand.getText();
    String model = txtModel.getText();
    String status = cmbStatus.getSelectedItem().toString();
    String priceStr = txtPrice.getText();

    // Validate input fields
    if (reg.isEmpty() || brand.isEmpty() || model.isEmpty() || status.isEmpty() || priceStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
    } else {
        try {
            int price = Integer.parseInt(priceStr);
            if (price <= 0) {
                JOptionPane.showMessageDialog(this, "Price must be a positive integer.", "Input Error", JOptionPane.ERROR_MESSAGE);
            } else {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ajcar", "Kaveen", "123");
                PreparedStatement add = con.prepareStatement("insert into cartbl values(?,?,?,?,?)");

                add.setString(1, reg);
                add.setString(2, brand);
                add.setString(3, model);
                add.setString(4, status);
                add.setInt(5, price);

                int row = add.executeUpdate();
                if (row > 0) {
                    JOptionPane.showMessageDialog(this, "Car Added Successfully");
                    Displaycars();
                    btnResetActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add car.", "Database Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price format. Please enter a valid integer.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
} catch (HeadlessException e) {
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}

    
               
               
               
           

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        Reg.setText(null);
                txtBrand.setText(null);
                txtModel.setText(null);
                txtPrice.setText(null);
                
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void lblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseClicked
//        // TODO add your handling code here:
//        Customer c = new Customer();
//        jPanel2.removeAll();
//        jPanel2.add(c).setVisible(true);
this.dispose();
Customer c = new Customer();
c.setVisible(true);
    }//GEN-LAST:event_lblCustomerMouseClicked

    private void lblRentCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRentCarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Rents r = new Rents();
        r.setVisible(true);
    }//GEN-LAST:event_lblRentCarMouseClicked

    private void lblReturnCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnCarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Return re = new Return();
        re.setVisible(true);
    }//GEN-LAST:event_lblReturnCarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new cars().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(cars.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Reg;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAjCarRental;
    private javax.swing.JLabel lblAjCarRental1;
    private javax.swing.JLabel lblAjCarRental2;
    private javax.swing.JLabel lblAjCarRental8;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRentCar;
    private javax.swing.JLabel lblReturnCar;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblCar;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
