/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrental;
import com.mysql.cj.protocol.Resultset;
import java.awt.HeadlessException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KAVEEN
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        display();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Connection con ;
    Statement st;
    Resultset Rs;
    PreparedStatement pst;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblAjCarRental = new javax.swing.JLabel();
        lblAjCarRental1 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblCars = new javax.swing.JLabel();
        lblRentCar = new javax.swing.JLabel();
        lblReturnCar = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        txtCustomerName = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        lblCustomerName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        lblCustomerList = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomersList = new javax.swing.JTable();
        lblManageCustomers = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        lblAjCarRental.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblAjCarRental.setForeground(new java.awt.Color(51, 51, 51));
        lblAjCarRental.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAjCarRental.setText("Service");
        lblAjCarRental.setName("lblAJCarRental"); // NOI18N

        lblAjCarRental1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblAjCarRental1.setForeground(new java.awt.Color(51, 51, 51));
        lblAjCarRental1.setText("AJ Car Rental");
        lblAjCarRental1.setName("lblAJCarRental"); // NOI18N

        lblImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\KAVEEN\\Desktop\\New folder (6)\\images_(2)-transformed.png")); // NOI18N

        lblCars.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblCars.setForeground(new java.awt.Color(255, 255, 255));
        lblCars.setText("Cars");
        lblCars.setName("lblAJCarRental"); // NOI18N
        lblCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarsMouseClicked(evt);
            }
        });

        lblRentCar.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblRentCar.setForeground(new java.awt.Color(255, 255, 255));
        lblRentCar.setText("Rent Car");
        lblRentCar.setName("lblAJCarRental"); // NOI18N
        lblRentCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRentCarMouseClicked(evt);
            }
        });

        lblReturnCar.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblReturnCar.setForeground(new java.awt.Color(255, 255, 255));
        lblReturnCar.setText("Return Car");
        lblReturnCar.setName("lblAJCarRental"); // NOI18N
        lblReturnCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReturnCarMouseClicked(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 51));
        btnLogout.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAjCarRental1)
                            .addComponent(lblCars)
                            .addComponent(lblRentCar)
                            .addComponent(lblReturnCar)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblAjCarRental))
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblImage)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAjCarRental1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAjCarRental)
                .addGap(125, 125, 125)
                .addComponent(lblCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRentCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReturnCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnClose.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 0, 51));
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
        );

        txtCustomerName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCustomerName.setForeground(new java.awt.Color(255, 0, 51));

        btnEdit.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 0, 51));
        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblCustomerName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(255, 0, 51));
        lblCustomerName.setText("Customer Name");
        lblCustomerName.setName("lblAJCarRental"); // NOI18N

        lblAddress.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 0, 51));
        lblAddress.setText("Address");
        lblAddress.setName("lblAJCarRental"); // NOI18N

        btnReset.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 51));
        btnReset.setText("Clear");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(255, 0, 51));

        lblCustomerList.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblCustomerList.setForeground(new java.awt.Color(255, 0, 51));
        lblCustomerList.setText("Customers List");
        lblCustomerList.setName("lblAJCarRental"); // NOI18N

        lblTelephone.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTelephone.setForeground(new java.awt.Color(255, 0, 51));
        lblTelephone.setText("Telephone");
        lblTelephone.setName("lblAJCarRental"); // NOI18N

        txtTelephone.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTelephone.setForeground(new java.awt.Color(255, 0, 51));

        tblCustomersList.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblCustomersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Address", "Telephone"
            }
        ));
        tblCustomersList.setRowHeight(25);
        jScrollPane1.setViewportView(tblCustomersList);

        lblManageCustomers.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblManageCustomers.setForeground(new java.awt.Color(255, 0, 51));
        lblManageCustomers.setText("Manage Customers");
        lblManageCustomers.setName("lblAJCarRental"); // NOI18N

        lblCustomerID.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCustomerID.setForeground(new java.awt.Color(255, 0, 51));
        lblCustomerID.setText("Customer ID");
        lblCustomerID.setName("lblAJCarRental"); // NOI18N

        txtCustomerID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCustomerID.setForeground(new java.awt.Color(255, 0, 51));

        btnDelete.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 0, 51));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(231, 231, 231))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(lblCustomerList)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(lblManageCustomers))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(btnsave)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblManageCustomers)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCustomerID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCustomerName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTelephone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnReset)
                    .addComponent(btnsave))
                .addGap(18, 18, 18)
                .addComponent(lblCustomerList)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
                
        
String url = "jdbc:mysql://localhost:3306/ajcar";
String username = "Kaveen";
String password = "123";

Connection connection = null; // Initialize the connection

try {
    connection = DriverManager.getConnection(url, username, password);

    String sql = "UPDATE customer SET CName = ?, CAddress = ?, CTelephone = ? WHERE CID = ?";
    PreparedStatement statement = connection.prepareStatement(sql);
    statement.setString(1, txtCustomerName.getText());
    statement.setString(2, txtAddress.getText());
    statement.setInt(3, Integer.parseInt(txtTelephone.getText()));
    statement.setString(4, txtCustomerID.getText());

    int rowsAffected = statement.executeUpdate();
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(null, "Updated successfully.");
        display();
        btnResetActionPerformed(evt);
        
    } else {
        JOptionPane.showMessageDialog(null, "No records were updated.", "Update Error", JOptionPane.WARNING_MESSAGE);
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
} catch (HeadlessException | NumberFormatException exception) {
    JOptionPane.showMessageDialog(null, "Data cannot be updated because of: " + exception, "Update Error", JOptionPane.ERROR_MESSAGE);
} finally {
    if (connection != null) {
        try {
            connection.close(); // Close the connection when done
        } catch (SQLException e) {
            // Handle any potential closing error
            e.printStackTrace();
        }
    }
}

    }//GEN-LAST:event_btnEditActionPerformed

    
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
                txtCustomerID.setText(null);
                txtCustomerName.setText(null);
                txtAddress.setText(null);
                txtTelephone.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/ajcar";
        String username = "Kaveen";
        String password = "123";

        // SQL query to delete voter details
        String sql = "DELETE FROM customer WHERE CID = ?";

        try (Connection conn = DriverManager.getConnection(url, username, password);
            PreparedStatement stmt = conn.prepareStatement(sql)) {
            String customers = txtCustomerID.getText();
            stmt.setString(1, customers);

            // Execute the delete query
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(rootPane, "user account deleted successfully.");
                display();
                btnResetActionPerformed(evt);
                
                

            } else {
                JOptionPane.showMessageDialog(rootPane, "No matching user details found.");

            }

        } catch (SQLException e) {
        }
        
        
        
       
    }//GEN-LAST:event_btnDeleteActionPerformed
public void display(){
     DefaultTableModel model = (DefaultTableModel) tblCustomersList.getModel();
        model.setRowCount(0);
    
        try {
            String url = "jdbc:mysql://localhost:3306/ajcar";
            String username = "Kaveen";
            String password = "123";

            try (Connection conn = DriverManager.getConnection(url, username, password)) {
                String sql = "SELECT * FROM customer";
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    
                    try (ResultSet rs = stmt.executeQuery()) {
                        while (rs.next()) {
                            String CusID = rs.getString("CID");
                            String CusName = rs.getString("CName");
                            String CusAddress = rs.getString("CAddress");
                            String CusTelephone = rs.getString("CTelephone");
                            Object[] rowData = { CusID, CusName, CusAddress, CusTelephone};
                            model.addRow(rowData);
                        }
                    }
                }
            }
        } catch (SQLException e) {
}
}
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

                try {
    String cid = txtCustomerID.getText();
    String cname = txtCustomerName.getText();
    String caddress = txtAddress.getText();
    String ctele = txtTelephone.getText();

    // Validate input fields
    if (cid.isEmpty() || cname.isEmpty() || caddress.isEmpty() || ctele.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
    } else {
        try {
            int CTelephone = Integer.parseInt(ctele);
            if (CTelephone <= 0) {
                JOptionPane.showMessageDialog(this, "Price must be a positive integer.", "Input Error", JOptionPane.ERROR_MESSAGE);
            } else {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ajcar", "Kaveen", "123");
                PreparedStatement add = con.prepareStatement("insert into customer values(?,?,?,?)");

                add.setString(1, cid);
                add.setString(2, cname);
                add.setString(3, caddress);
                add.setInt(4, CTelephone);

                int row = add.executeUpdate();
                if (row > 0) {
                    JOptionPane.showMessageDialog(this, "Customer Added Successfully");
                    display();
                    btnResetActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add Customer.", "Database Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price format. Please enter a valid integer.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
} catch (HeadlessException e) {
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void lblCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        try{
         cars c = new cars();
        c.setVisible(true);}
        catch(Exception e){
        
        }
         
    }//GEN-LAST:event_lblCarsMouseClicked

    private void lblRentCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRentCarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Rents re = new Rents();
        re.setVisible(true);
    }//GEN-LAST:event_lblRentCarMouseClicked

    private void lblReturnCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnCarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Return re = new Return();
        re.setVisible(true);
    }//GEN-LAST:event_lblReturnCarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnsave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAjCarRental;
    private javax.swing.JLabel lblAjCarRental1;
    private javax.swing.JLabel lblCars;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerList;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblManageCustomers;
    private javax.swing.JLabel lblRentCar;
    private javax.swing.JLabel lblReturnCar;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JTable tblCustomersList;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
